- name: Build Android Release (apk)
        run: |
          cd android
          if [ -f "gradlew" ]; then
            chmod +x gradlew
            # تم التغيير لـ assembleRelease للحصول على نسخة رسمية قابلة للتوقيع
            ./gradlew assembleRelease --stacktrace
          else
            echo "Gradlew missing. Falling back to system Gradle..."
            gradle assembleRelease --stacktrace
          fi

      - name: Sign apk
        uses: r0adkll/sign-android-release@v1
        id: sign_app
        with:
          # ✅ تم تصحيح المسار ليبحث في مجلد الـ apk وليس الـ bundle
          releaseDirectory: android/app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.KEYSTORE_BASE64 }}
          alias: ${{ secrets.KEY_ALIAS }}
          keyStorePassword: ${{ secrets.KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}

      - name: Upload Signed apk
        uses: actions/upload-artifact@v4
        with:
          name: Rased-Teacher-Signed-apk
          # سيقوم برفع الملف الموقّع الذي أنتجته خطوة التوقيع
          path: ${{steps.sign_app.outputs.signedReleaseFile}}
